{
 "title": "V2ray",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(user_traffic_down, host)"
   },
   {
    "name": "user",
    "label": "User:",
    "query": "label_values(user_traffic_down, name)"
   },
   { "name": "period", "label": "Period(day):", "query": "30d,1d,7d,14d,60d,90d,180d,1y" }
  ]
 },
 "panels": [
  {
   "title": "Host($host) Bandwidth (Last $period)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(user_traffic_down{host=~\"$host\"}[$period]))",
     "legendFormat": "[Download] $host"
    },
    {
     "expr": "-1 * sum(increase(user_traffic_up{host=~\"$host\"}[$period]))",
     "legendFormat": "[Upload] $host"
    }
   ]
  },
  {
   "title": "Host($host) Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(user_traffic_down{host=~\"$host\"}[1m]))",
     "legendFormat": "[Download] $host"
    },
    {
     "expr": "-1 * sum(irate(user_traffic_up{host=~\"$host\"}[1m]))",
     "legendFormat": "[Upload] $host"
    }
   ]
  },
  {
   "title": "User($user)@Host($host) Bandwidth (Last $period)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(user_traffic_down{name=~\"$user\",host=~\"$host\"}[$period])",
     "legendFormat": "[Download] {{name}}@{{host}}"
    },
    {
     "expr": "-1 * increase(user_traffic_up{name=~\"$user\",host=~\"$host\"}[$period])",
     "legendFormat": "[Upload] {{name}}@{{host}}"
    }
   ]
  },
  {
   "title": "User($user)@Host($host) Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(user_traffic_down{name=~\"$user\",host=~\"$host\"}[1m])",
     "legendFormat": "[Download] {{name}}@{{host}}"
    },
    {
     "expr": "-1 * irate(user_traffic_up{name=~\"$user\",host=~\"$host\"}[1m])",
     "legendFormat": "[Upload] {{name}}@{{host}}"
    }
   ]
  }
 ]
}